version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: personal_record_php
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: personal_record_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
    driver: local
